spring:
    application:
        name: Jejumate_BE

jwt:
    secret-key: ${JWT_SECRET_KEY}
    access-token-expiration-ms: 3600000 # 1??
    refresh-token-expiration-ms: 1209600000 # 14?

kakao:
    client-id: ${KAKAO_CLIENT_ID}
    client-secret: ${KAKAO_CLIENT_SECRET}
    token-uri: https://kauth.kakao.com/oauth/token
    user-info-uri: https://kapi.kakao.com/v2/user/me
    redirect-uri: ${KAKAO_REDIRECT_URI}
